services:
  - type: web
    name: careerai-frontend
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    envVars:
      - key: VITE_API_URL
        value: https://careerai-backend-iakw.onrender.com/api
    routes:
      - type: rewrite
        source: /*
        destination: /index.html